name: Nix Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix with root procedure
      run: |
        # Get installer
        curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install -o /tmp/nix_installer.sh
        chmod 755 /tmp/nix_installer.sh
        # Install Nix using the root procedure
        sudo sh /tmp/nix_installer.sh --daemon
        
        # Enable flakes and nix-command and caches
        sudo ./scripts/nix-command-edit.sh
        
        # Add nix to PATH
        echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH

        # reboot the daemon
        sudo systemctl restart nix-daemon
    - name: Build registered derivations
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        NIX_SIGN_KEY: ${{ secrets.NIX_SIGN_KEY }}
      run: |
        # build everything
        source ./ci/ci_build.sh
        echo " test ${{ secrets.NIX_SIGN_KEY }}" 
        build_all_derivation



